solr:
  build: ./solr/
  ports:
    - "8983:8983"

dev1:
  build: ./web/
  environment:
    MYSQL_ROOT_PASSWORD: pwd
    MYSQL_USER: root
    MYSQL_DATABASE: dev1
    MYSQL_HOST: 1.1.1.1
    GIT_BRANCH: master
    UPDATE_DB: 1
    MYSQL_PASSWORD: 123
  ports:
   - "1.1.1.1:8003:80"
  volumes:
   - /tmp/dev1:/var/www/html
  links:
   - solr
