solr:
  build: ./solr/
  ports:
    - "8983:8983"

dev1:
  build: ./web/
  environment:
    MYSQL_ROOT_PASSWORD: pwd
    MYSQL_USER: user
    MYSQL_DATABASE: dev1
    MYSQL_HOST: 1.1.1.1
  ports:
   - "8003:80"
  volumes:
   - /tmp/dev1:/var/www/html
  links:
   - solr